# Generated by Django 4.1.1 on 2022-10-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_product_brand_alter_product_category'),
        ('stock', '0002_alter_transaction_price_total'),
    ]

    operations = [
    ]
